#include "LightTreeReader.hh"
#include <iomanip>
#include <iostream>

LightTreeReader::LightTreeReader(){
  tree_ = 0;
  
 run_=-1;
lumi_=-1;
event_=-1;
weight_nolep_=1;
total_weight_lepveto_ = 1;
total_weight_leptight_ = 1;
puweight_up_scale_=1;
puweight_down_scale_=1;
jet1_pt_ = 0;
jet2_pt_ = 0;
jet3_pt_=-1;
jet1_E_ = 0;
jet2_E_ = 0;
jet3_E_ = 0;
jet1_eta_ = 0;
jet2_eta_ = 0;
jet3_eta_ = 0;
jet1_phi_ = 0;
jet2_phi_ = 0;
jet3_phi_ = 0;
jet1_csv_ = 0;
jet2_csv_ = 0;
jet3_csv_ = 0;
dijet_M_ = 0;
dijet_deta_ = 0;
dijet_sumeta_ = 0;
dijet_dphi_ = 0;
met_ = 0;
met_x_ = 0;
met_y_ = 0;
metnomu_x_ = 0;
metnomu_y_ = 0;
met_significance_ = 0;
metnomu_significance_ = 0;
sumet_ = 0;
ht_ = 0;
ht30_ = 0;
mht_ = 0;
sqrt_ht_ = 0;
unclustered_et_ = 0;
jet1met_dphi_ = 0;
jet2met_dphi_ = 0;
jet1metnomu_dphi_ = 0;
jet2metnomu_dphi_ = 0;
jetmet_mindphi_ = 0;
jetmetnomu_mindphi_ = 0;
alljetsmet_mindphi_ = 0;
alljetsmetnomu_mindphi_ = 0;
jetunclet_mindphi_ = 0;
metunclet_dphi_ = 0;
metnomuunclet_dphi_ = 0;
dijetmet_scalarSum_pt_ = 0;
 dijetmet_vectorialSum_pt_ = 0;
dijetmet_ptfraction_ = 0;
jet1met_scalarprod_ = 0;
jet2met_scalarprod_ = 0;
dijetmetnomu_scalarSum_pt_ = 0;
dijetmetnomu_vectorialSum_pt_ = 0;
dijetmetnomu_ptfraction_ = 0;
jet1metnomu_scalarprod_ = 0;
jet2metnomu_scalarprod_ = 0;
n_jets_cjv_30_ = 0;
n_jets_cjv_20EB_30EE_ = 0;
cjvjetpt_=-1;
passtrigger_ = -1;
passparkedtrigger1_ = -1;
passparkedtrigger2_ = -1;
l1met_ = 0;
metnomuons_ =0;
nvetomuons_=0;
nselmuons_=0;
nvetoelectrons_=0;
nselelectrons_=0;
ntaus_=0;
m_mumu_=-1;
m_mumu_gen_=-1;
mu1_pt_=-1;
mu1_eta_=-10000;
mu1_phi_=-1;
mu2_pt_=-1;
mu2_eta_=-10000;
mu2_phi_=-1;
ele1_pt_=-1;
ele1_eta_=-10000;
ele1_phi_=-1;
tau1_pt_=-1;
tau1_eta_=-10000;
tau1_phi_=-1;
lep_mt_=-1;
n_vertices_=-1;
  
}

LightTreeReader::~LightTreeReader(){
  ;
}

void LightTreeReader::SetBranchAddresses(){
  if (!tree_) {
    std::cout << " -- ERROR! Tree pointer is 0." << std::endl;
    exit(1);
  }

 tree_->SetBranchAddress("run",&run_);
tree_->SetBranchAddress("lumi",&lumi_);
tree_->SetBranchAddress("event",&event_);
tree_->SetBranchAddress("weight_nolep",&weight_nolep_);
tree_->SetBranchAddress("total_weight_lepveto",&total_weight_lepveto_);
tree_->SetBranchAddress("total_weight_leptight",&total_weight_leptight_);
tree_->SetBranchAddress("puweight_up_scale",&puweight_up_scale_);
tree_->SetBranchAddress("puweight_down_scale",&puweight_down_scale_);
tree_->SetBranchAddress("jet1_pt",&jet1_pt_);
tree_->SetBranchAddress("jet2_pt",&jet2_pt_);
tree_->SetBranchAddress("jet3_pt",&jet3_pt_);
tree_->SetBranchAddress("jet1_E",&jet1_E_);
tree_->SetBranchAddress("jet2_E",&jet2_E_);
tree_->SetBranchAddress("jet3_E",&jet3_E_);
tree_->SetBranchAddress("jet1_eta",&jet1_eta_);
tree_->SetBranchAddress("jet2_eta",&jet2_eta_);
tree_->SetBranchAddress("jet3_eta",&jet3_eta_);
tree_->SetBranchAddress("jet1_phi",&jet1_phi_);
tree_->SetBranchAddress("jet2_phi",&jet2_phi_);
tree_->SetBranchAddress("jet3_phi",&jet3_phi_);
tree_->SetBranchAddress("jet1_csv",&jet1_csv_);
tree_->SetBranchAddress("jet2_csv",&jet2_csv_);
tree_->SetBranchAddress("jet3_csv",&jet3_csv_);
tree_->SetBranchAddress("dijet_M",&dijet_M_);
tree_->SetBranchAddress("dijet_deta",&dijet_deta_);
tree_->SetBranchAddress("dijet_sumeta",&dijet_sumeta_);
tree_->SetBranchAddress("dijet_dphi",&dijet_dphi_);
tree_->SetBranchAddress("met",&met_);
tree_->SetBranchAddress("met_x",&met_x_);
tree_->SetBranchAddress("met_y",&met_y_);
tree_->SetBranchAddress("metnomu_x",&metnomu_x_);
tree_->SetBranchAddress("metnomu_y",&metnomu_y_);
tree_->SetBranchAddress("met_significance",&met_significance_);
tree_->SetBranchAddress("metnomu_significance",&metnomu_significance_);
tree_->SetBranchAddress("sumet",&sumet_);
tree_->SetBranchAddress("ht",&ht_);
tree_->SetBranchAddress("ht30",&ht30_);
tree_->SetBranchAddress("mht",&mht_);
tree_->SetBranchAddress("sqrt_ht",&sqrt_ht_);
tree_->SetBranchAddress("unclustered_et",&unclustered_et_);
tree_->SetBranchAddress("jet1met_dphi",&jet1met_dphi_);
tree_->SetBranchAddress("jet2met_dphi",&jet2met_dphi_);
tree_->SetBranchAddress("jet1metnomu_dphi",&jet1metnomu_dphi_);
tree_->SetBranchAddress("jet2metnomu_dphi",&jet2metnomu_dphi_);
tree_->SetBranchAddress("jetmet_mindphi",&jetmet_mindphi_);
tree_->SetBranchAddress("jetmetnomu_mindphi",&jetmetnomu_mindphi_);
 tree_->SetBranchAddress("alljetsmet_mindphi",&alljetsmet_mindphi_);
tree_->SetBranchAddress("alljetsmetnomu_mindphi",&alljetsmetnomu_mindphi_);
tree_->SetBranchAddress("jetunclet_mindphi",&jetunclet_mindphi_);
tree_->SetBranchAddress("metunclet_dphi",&metunclet_dphi_);
tree_->SetBranchAddress("metnomuunclet_dphi",&metnomuunclet_dphi_);
tree_->SetBranchAddress("dijetmet_scalarSum_pt",&dijetmet_scalarSum_pt_);
tree_->SetBranchAddress("dijetmet_vectorialSum_pt",&dijetmet_vectorialSum_pt_);
tree_->SetBranchAddress("dijetmet_ptfraction",&dijetmet_ptfraction_);
tree_->SetBranchAddress("jet1met_scalarprod",&jet1met_scalarprod_);
tree_->SetBranchAddress("jet2met_scalarprod",&jet2met_scalarprod_);
tree_->SetBranchAddress("dijetmetnomu_scalarSum_pt",&dijetmetnomu_scalarSum_pt_);
tree_->SetBranchAddress("dijetmetnomu_vectorialSum_pt",&dijetmetnomu_vectorialSum_pt_);
tree_->SetBranchAddress("dijetmetnomu_ptfraction",&dijetmetnomu_ptfraction_);
tree_->SetBranchAddress("jet1metnomu_scalarprod",&jet1metnomu_scalarprod_);
tree_->SetBranchAddress("jet2metnomu_scalarprod",&jet2metnomu_scalarprod_);
tree_->SetBranchAddress("n_jets_cjv_30",&n_jets_cjv_30_);
tree_->SetBranchAddress("n_jets_cjv_20EB_30EE",&n_jets_cjv_20EB_30EE_);
tree_->SetBranchAddress("cjvjetpt",&cjvjetpt_);
tree_->SetBranchAddress("passtrigger",&passtrigger_);
tree_->SetBranchAddress("passparkedtrigger1",&passparkedtrigger1_);
tree_->SetBranchAddress("passparkedtrigger2",&passparkedtrigger2_);
tree_->SetBranchAddress("l1met",&l1met_);
tree_->SetBranchAddress("metnomuons",&metnomuons_);
tree_->SetBranchAddress("nvetomuons",&nvetomuons_);
tree_->SetBranchAddress("nselmuons",&nselmuons_);
tree_->SetBranchAddress("nvetoelectrons",&nvetoelectrons_);
tree_->SetBranchAddress("nselelectrons",&nselelectrons_);
tree_->SetBranchAddress("ntaus",&ntaus_);
tree_->SetBranchAddress("m_mumu",&m_mumu_);
tree_->SetBranchAddress("m_mumu_gen",&m_mumu_gen_);
tree_->SetBranchAddress("mu1_pt",&mu1_pt_);
tree_->SetBranchAddress("mu1_eta",&mu1_eta_);
tree_->SetBranchAddress("mu1_phi",&mu1_phi_);
tree_->SetBranchAddress("mu2_pt",&mu2_pt_);
tree_->SetBranchAddress("mu2_eta",&mu2_eta_);
tree_->SetBranchAddress("mu2_phi",&mu2_phi_);
tree_->SetBranchAddress("ele1_pt",&ele1_pt_);
tree_->SetBranchAddress("ele1_eta",&ele1_eta_);
tree_->SetBranchAddress("ele1_phi",&ele1_phi_);
tree_->SetBranchAddress("tau1_pt",&tau1_pt_);
tree_->SetBranchAddress("tau1_eta",&tau1_eta_);
tree_->SetBranchAddress("tau1_phi",&tau1_phi_);
tree_->SetBranchAddress("lep_mt",&lep_mt_);
tree_->SetBranchAddress("n_vertices",&n_vertices_);

}
